### ISSUE TITLE
SvelteKit new routing

### ISSUE THREAD

**Issue by paolodina** [extragood-io/svelte-kit-navigation#1]
Hello, I guess (?) the tutorial is no longer valid due to https://github.com/sveltejs/kit/discussions/5748.

Will you update the tutorial/code to reflect the recent changes to SvelteKit routing system?

**Comment by debussyman** [comment]
Absolutely! I'll work on getting it updated

**Comment by debussyman** [comment]
Code is updated to the latest version of SvelteKit (next.483)! It required a two-step migration, but is now compatible with the new routing system. I'll also update the blog post shortly

**Comment by paolodina** [comment]
@debussyman greatly appreciated, thanks.
